[package]
name = "talon-rs"
version = "0.1.0"
authors = ["Devon McKenzie <novithian@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
